### PR TITLE
Bump Rubies: 1.9.3-p551, 2.0.0-p645, 2.1.6, and add 2.2.2

### PR DESCRIPTION
**Pull request by sodabrew**
I was not able to build Ruby 2.2.1 using RVM 1.9.3, so I switched to RVM 2.0.0 for the 2.2.1 builds. Now they fail in a novel way - apparently trying to load a Windows DLL at build time:

```
ruby --disable=gems -I/home/vagrant/.rake-compiler/builds/i686-w64-mingw32/ruby-2.2.1 -ri386-mingw32-fake  -I`cd /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib; pwd` --disable-gems -r./i386-mingw32-fake /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb --make="make -j2" --dest-dir="" --extout=".ext" --mflags="- --jobserver-fds=4,5 -j" --make-flags=" --jobserver-fds=4,5 -j" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc"
installing binary commands:   /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/bin
installing base libraries:    /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib
installing arch files:        /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/2.2.0/i386-mingw32
installing pkgconfig data:    /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/pkgconfig
installing command scripts:   /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/bin
installing library scripts:   /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/2.2.0
installing common headers:    /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/include/ruby-2.2.0
installing manpages:          /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/share/man/man1
installing extension objects: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/2.2.0/i386-mingw32
installing extension objects: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/i386-msvcrt
installing extension objects: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0/i386-msvcrt
installing extension headers: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/include/ruby-2.2.0/i386-mingw32
installing extension scripts: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/2.2.0
installing extension scripts: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/site_ruby/2.2.0
installing extension scripts: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/vendor_ruby/2.2.0
installing extension headers: /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/include/ruby-2.2.0/ruby
installing default gems:      /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.2.6
                              io-console 0.4.3
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /home/vagrant/.rake-compiler/ruby/i686-w64-mingw32/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
/home/vagrant/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fiddle/import.rb:85:in `rescue in block in dlload': can't load advapi32 (Fiddle::DLError)
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fiddle/import.rb:82:in `block in dlload'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fiddle/import.rb:73:in `collect'
	from /home/vagrant/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/fiddle/import.rb:73:in `dlload'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:48:in `<module:AdvApi32>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:46:in `<module:SecureRandom>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:42:in `<top (required)>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/resolv.rb:6:in `<top (required)>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/remote_fetcher.rb:6:in `<top (required)>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/spec_fetcher.rb:1:in `<top (required)>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/dependency_installer.rb:5:in `<top (required)>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems.rb:556:in `install'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:721:in `each'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:721:in `block in <main>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:757:in `call'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:757:in `block in <main>'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:754:in `each'
	from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-nodoc] Error 1
```

### CODE REVIEW

**Comment by sodabrew** [comment]
Looks like it's happening here:
```
    from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:48:in `<module:AdvApi32>'
```
At build time, this module thinks it is running on Windows. I'm kind of confused.
``` ruby
module SecureRandom
  if /mswin|mingw/ =~ RUBY_PLATFORM
    require "fiddle/import"

    module AdvApi32 # :nodoc:
      extend Fiddle::Importer
      dlload "advapi32"
      extern "int CryptAcquireContext(void*, void*, void*, unsigned long, unsigned long)"
      extern "int CryptGenRandom(void*, unsigned long, void*)"
...
```

**Comment by sodabrew** [comment]
Ping @unak - https://github.com/ruby/ruby/commit/b2247be9931a16ce55e1e8fccc41ca22aaf680f5

**Comment by luislavena** [comment]
@tjschuck @sodabrew `i386-mingw32-fake` redefined `RUBY_PLATFORM` to be mingw, so that makes cross-compilation installation to fail.

Seems that the check around `@has_win32` has been removed which I believe was used to determine if you're really running under Windows or not.

I cannot help further than that.

**Comment by unak** [comment]
Should be as this?

```Ruby
  if !defined(OpenSSL::Random) && /mswin|mingw/ =~ RUBY_PLATFORM
```

**Comment by sodabrew** [comment]
I will try that soon.

**Comment by sodabrew** [comment]
@unak Yes, your suggested change in https://github.com/tjschuck/rake-compiler-dev-box/pull/20#issuecomment-77636958 works.

**Comment by knu** [comment]
Doesn't bootstrap.sh need `$as_vagrant 'rvm install 2.2'` too?

**Comment by sodabrew** [comment]
@knu I'm not sure about bootstrap.sh - @tjschuck ?

**Comment by knu** [comment]
Seems I needed it (native ruby 2.2.1) in order for a cross ruby 2.2.1 to build and install.

**Comment by sodabrew** [comment]
A slate of new Rubies are out today, including the OpenSSL fix for the 2.2 series!
http://svn.ruby-lang.org/repos/ruby/tags/v2_2_2/ChangeLog

I'll update the PR soon for these new versions.

**Comment by sodabrew** [comment]
This PR builds the mysql2 gem out of the box. Let me know if I should squash the commits?

```
$ vagrant up
$ vagrant ssh
$ package_win32_fat_binary mysql2-sodabrew
# sudo make me a sandwich
$  find /vagrant/mysql2-sodabrew/pkg/ | egrep '\.so$'
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x64-mingw32/lib/mysql2/2.0/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x64-mingw32/lib/mysql2/2.1/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x64-mingw32/lib/mysql2/2.2/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mingw32/lib/mysql2/1.8/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mingw32/lib/mysql2/1.9/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mingw32/lib/mysql2/2.0/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mingw32/lib/mysql2/2.1/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mingw32/lib/mysql2/2.2/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mswin32-60/lib/mysql2/1.8/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mswin32-60/lib/mysql2/1.9/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mswin32-60/lib/mysql2/2.0/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mswin32-60/lib/mysql2/2.1/mysql2.so
/vagrant/mysql2-sodabrew/pkg/mysql2-0.3.18-x86-mswin32-60/lib/mysql2/2.2/mysql2.so
```

**Comment by sodabrew** [comment]
Squashed. I moved the `unzip` deb to a separate PR in case that raised concerns.

**Comment by knu** [comment]
This is working great!

**Comment by aharpervc** [comment]
Why are you rvm installing 2.2 as a system ruby? Is it used anywhere?

**Comment by sodabrew** [comment]
It was requested by someone on the ticket. I believe it can be used by other types of builds besides the default win32 build scripts.

**Comment by sodabrew** [comment]
@tjschuck Could you review this for merge?

**Comment by aharpervc** [comment]
@sodabrew well @knu mentioned it, but as you had written in the pr, only >= 2.0 is require to build 2.2+. So I do not believe it is necessary.

**Comment by zrisher** [comment]
What's the status off this PR's review? Would love to get Nokogiri building with Ruby 2.2 on Windows.

**Comment by larskanis** [comment]
[rake-compiler-dock](https://github.com/larskanis/rake-compiler-dock) already supports ruby-2.2. You build nokogiri for instance per rake-compiler-dock command like this:
``` sh
git clone https://github.com/sparklemotion/nokogiri/
cd nokogiri
rake-compiler-dock bash -c "bundle && rake cross native gem RUBY_CC_VERSION=1.9.3:2.0.0:2.1.6:2.2.2"
```
Or, since commands and additional environment settings vary between different gems, it's best to add this to the gem's Rakefile like in this [PR for nokogiri](https://github.com/sparklemotion/nokogiri/pull/1302) or other gems listed in the [wiki](https://github.com/larskanis/rake-compiler-dock/wiki/Projects-using-rake-compiler-dock).

**Comment by aharpervc** [comment]
https://github.com/rails-sqlserver/rake-compiler-dev-box also includes this PR

**Comment by tjschuck** [comment]
@sodabrew Thanks for the PR, and sorry for the delay.

There have been some subsequent updates, so I bumped the Ruby versions separately in e17131c2fcc284f3ac25a6096e973e957081fa91 and a2aa96989f0f9f5a4e1c8945103b96c63c632d65.  Closing this in favor of those.

Thanks again!

**Pull request closed without merging**
