### PR TITLE
Add instructions to maximize CPU and RAM of built VM

### PR DESCRIPTION
**Pull request by vassilevsky**
Default Vagrant images don't make very good build servers :)

### CODE REVIEW

**Comment by tjschuck** [comment]
@vassilevsky Do you have any benchmarks for these changes actually helping?

On my machine (MacBook Air, 1.7 GHz Intel Core i7, 8 GB RAM), these changes didn't do much.  `time prepare_xrubies`, the part of the build that takes the longest, did not change by a significant amount (not to mention that the results are saved and early-aborted when possible, so it doesn't have to be run again for subsequent builds).

The time to complete `vagrant up` fresh (i.e. after a `vagrant destroy`) improved a bit, but I'm not sure it improved enough to mandate these changes as defaults.  I assume the Vagrant team has done significantly more research and benchmarking for intelligent defaults, so I'm inclined to trust them...

/cc @luislavena @simi -- wondering if you saw any improvements either.

**Comment by luislavena** [comment]
@tjschuck I have no particular opinion about this and the change introduced didn't improve performance on my end either.

**Comment by vassilevsky** [comment]
Thanks for taking the time to review my changes. This was just a logical thing to do. But if you think this is unnecessary, feel free to close it. You're the boss!

**Comment by tjschuck** [comment]
@vassilevsky Haha, I'm nobody's boss!  Mostly just wondering if you saw performance gains that I didn't from these changes.

For the sake of simplicity, I'm going to close this -- there are a _lot_ of customizations one can make to their Vagrant/VM setup, and I don't know that we should necessarily prescribe them (or even worse, try to duplicate all of the Vagrant docs here).

Regardless, my endless thanks!  :heart: :heart: :heart_eyes_cat: :heart:

**Pull request closed without merging**
